# Generated by Django 4.0 on 2021-12-16 05:47

import backend.enums
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(default=backend.enums.OrderStatus['WAITING'])),
                ('deliver_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.customuser')),
                ('foods', models.ManyToManyField(to='backend.Food')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
